<% 
  years = []
  Time.now.year.downto 1990 do |year|
    
    if year == 1990
      years << "1990.."
    else
      years << year
    end
  end
%>
filter:
  status: [["All", "all"], ["Finish", "finish"], ["Unfinish", "unfinish"]]
  sort_movies: [["Update", 0], ["Views", 1], ["Rating", 2]]
  quality: [["mHD", "mHD"], ["HD", "HD"], ["BluRay", "BluRay"]]
  years: <%= years %>
