filter:
  status: [["all", "all"], ["finished", "finished"], ["unfinished", "unfinished"]]
  sort_movies: [["date update", 0], ["views", 1], ["rating", 2]]
  quality: [["mHD", "mHD"], ["HD", "HD"], ["BluRay", "BluRay"]]
