<%
  years = []
  now_year = Time.new.year
  years<<["All", 0]
  (now_year).downto(2005).each_with_index do |year, index|
    if year == 2005
      years<<["2005..",index+1]
    elsif
      years<<[year, index+1]
    end
  end
%>
filter:
  progress: [["All", 0], ["Finished", 1], ["In process", 2]]
  sort_movies: [["Time update", 0], ["View", 1], ["Rating", 2]]
  years: <%= years %>
